create question
Advanced-Frontend/Daily-Interview-Question pull request #136
Opened 2019-05-31 09:58 UTC by blockmood

2019-06-03 02:37 UTC, 5SSS commented
```javascript
function anwser (arr, target) {
  let map = {}
  for (let i = 0; i < arr.length; i++) {
    map[arr[i]] = i
  }
  for (let i = 0; i < arr.length; i++) {
    var d = target - arr[i]
    if (map[d]) {
      return [i, map[d]]
    }
  }
  return new Error('404 not found')
}
```

2019-06-03 04:56 UTC, harmsworth commented
var twoSum = function(nums, target) {
    const res = []
    loop:
    for (let i =0; i<nums.length-1; i++){
        for (let j = i+1;j<nums.length;j++){
            if (nums[i]+nums[j]===target){
                res.push(i,j)
                break loop
            }
        }
    }
    return res
};

2019-06-03 05:00 UTC, harmsworth commented
`var twoSum = function(nums, target) {
    const res = []
    loop:
    for (let i =0; i<nums.length-1; i++){
        for (let j = i+1;j<nums.length;j++){
            if (nums[i]+nums[j]===target){
                res.push(i,j)
                break loop
            }
        }
    }
    return res
};`

2019-06-03 05:06 UTC, harmsworth commented
```js
var twoSum = function(nums, target) {
    const res = []
    loop:
    for (let i =0; i<nums.length-1; i++){
        for (let j = i+1;j<nums.length;j++){
            if (nums[i]+nums[j]===target){
                res.push(i,j)
                break loop
            }
        }
    }
    return res
};
```

2019-06-03 05:50 UTC, liuxinyea commented
> ```js
> function anwser (arr, target) {
>   let map = {}
>   for (let i = 0; i < arr.length; i++) {
>     map[arr[i]] = i
>   }
>   for (let i = 0; i < arr.length; i++) {
>     var d = target - arr[i]
>     if (map[d]) {
>       return [i, map[d]]
>     }
>   }
>   return new Error('404 not found')
> }
> ```
return [arr[i], map[d]]

2019-06-03 06:26 UTC, lvwxx commented
function sum(arr, target) {
  const res = []
  for (let i = 0; i < arr.length; i++){
    const a = target - arr[i]
    const index = arr.indexOf(a,i)
    if (index>=0) {
      res.push(i, index)
    }
  }
  return res
}

2019-06-03 07:18 UTC, Mikerui commented
function twoSums(nums, target) {
  let subtract
  for (let j = 0; j < nums.length; j++) {
    subtract = target - nums[j]
    for (let i = 0; i < nums.length; i++) {
      if (nums[i] == subtract && i !== j) {
        return [j, i]
      } else {
        continue
      }
    }
  }
  return false
}

2019-06-03 07:18 UTC, Mikerui commented
`function twoSums(nums, target) {
  let subtract
  for (let j = 0; j < nums.length; j++) {
    subtract = target - nums[j]
    for (let i = 0; i < nums.length; i++) {
      if (nums[i] == subtract && i !== j) {
        return [j, i]
      } else {
        continue
      }
    }
  }
  return false
}`

2019-06-03 07:19 UTC, blockmood commented
@Mikerui  队形！

2019-06-03 08:14 UTC, KimberlyZou commented
var twoSum = function(nums, target) {
  for (i = 0; i < nums.length; i++) {
    var sheng = target - nums[i];
    if (nums.indexOf(sheng) != -1 && nums.indexOf(sheng) != i) {
      return [i, nums.indexOf(sheng)];
    }
  }
};

2019-06-03 10:25 UTC, nssol-fengzhichao commented
> 
> 
> ```js
> function anwser (arr, target) {
>   let map = {}
>   for (let i = 0; i < arr.length; i++) {
>     map[arr[i]] = i
>   }
>   for (let i = 0; i < arr.length; i++) {
>     var d = target - arr[i]
>     if (map[d]) {
>       return [i, map[d]]
>     }
>   }
>   return new Error('404 not found')
> }
> ```

没考虑重复啊

2019-06-03 15:04 UTC, gaoyafengyagao commented
var arr = [2,3,4,1,6,9,0,7],target = 9;
		function answer(array,target){
			for(let i=0;i<array.length;i++){
				let a = target - array[i];
				let res = array.indexOf(a,i)
				if(res>-1){
					console.log(a + "+" + array[i]+"="+9)
				}
			}
		}
		answer(arr,target)

2019-06-03 15:10 UTC, cleverboy32 commented
arr.reduce((res, cval, index) => {
     if ( res.indexOf(cval) !== -1 ) return;
     arr.indexOf(cval) !== -1 && res = res.concat([cval, target-cval]);
}, []);

2019-06-03 17:22 UTC, lhyt commented
这样太简单了，直接index解决：
```javascript
arr.reduce((res, cur, i) => {
	const index =  arr.findIndex(x => x === target - cur);
	return res || (!!~ index && [i, index])
}, void 0);
```

题目可以增加一点难度，找出arr中所有的和为target的元素子集：
```javascript
function findTarget(arr, target) {
	const res = { idx: [], ele: [] };
	!function dp(target, index, memoryIndex = [], memoryEle = []) {
		const remain = target - arr[index];
		if (remain === 0) {
			res.idx.push(memoryIndex);
			res.ele.push(memoryEle);
		}
		if (index + 1 >= arr.length) {
			return;
		}
		for (let i = index + 1; i < arr.length; i++ ) {
			dp(remain, i, [...memoryIndex, i], [...memoryEle, arr[i]])
		}
	}(target, 0, [0], [arr[0]]);
	return res;
}
```

2019-06-04 02:27 UTC, Vera1128 commented
> ```js
> function sum(arr, target) {
>   const res = []
>   for (let i = 0; i < arr.length; i++){
>     const a = target - arr[i]
>     const index = arr.indexOf(a,i)
>     if (index>=0) {
>       res.push(i, index)
>     }
>   }
>   return res
> }
> ```
> 
> _循环一次_

当arr = [4, 7, 11, 15], target = 8的时候会有问题，结果是[0, 0]， 显然是有问题的

2019-06-04 02:44 UTC, NewPrototype commented
```
function sum(arr:number[],target:number):number[]{
  const len:number=arr.length;
  let index:number=0;
  let disabled:number[]=[];
  let result:number[]=[];
  while (index<len) {
      const endIndex=arr.findIndex((v,i)=>{
          return i!=index&&v+arr[index]==target
      })
      if(endIndex>-1&&!disabled.includes(endIndex)){
        disabled.push(index,endIndex)
        result.push(index,endIndex);
      }
    index++
  }
  return result 
}
```
```
  it('sum([2, 7, 11, 15,8,2,1],9) to toEqual [0,1,4,6]', () => {
    expect(sum([2, 7, 11, 15,8,2,1],9)).toEqual([0,1,4,6]);
  });
  it('sum([2, 7, 11, 15,8,2,1,5,5],10) to toEqual [0,4,7,8]', () => {
    expect(sum([2, 7, 11, 15,8,2,1,5,5],10)).toEqual([0,4,7,8]);
  });
```

2019-06-04 03:28 UTC, BaconZhang commented
可以使用二分查找来提高效率
```javascript
var twoSum = (nums, target) => {
	if (nums.length < 2) {
		throw new Error("至少提供两个数字")
	}
	if (nums.length === 2) {
		if (nums[0] + nums[1] === target) {
			return nums;
		}
		throw new Error("没找到")
	}
	nums = nums.sort((a, b) => a - b);
	let l = Math.floor(nums.length / 2);
	let s = l -1;
	while(s >= 0 && l <= nums.length - 1) {
		let a = nums[s]
		let b = nums[l]
		if (a + b < target) {
			l = Math.floor((l + nums.length - 1) / 2);
			continue;
		} else if (a + b > target) {
			s = Math.floor((s + 0) / 2);
		} else {
			return [a, b]
		}
	}
	throw new Error("没找到")
}
```

2019-06-04 07:51 UTC, Francecil commented
> 可以使用二分查找来提高效率
> 
> ```js
> var twoSum = (nums, target) => {
> 	if (nums.length < 2) {
> 		throw new Error("至少提供两个数字")
> 	}
> 	if (nums.length === 2) {
> 		if (nums[0] + nums[1] === target) {
> 			return nums;
> 		}
> 		throw new Error("没找到")
> 	}
> 	nums = nums.sort((a, b) => a - b);
> 	let l = Math.floor(nums.length / 2);
> 	let s = l - 1;
> 	while(s >= 0 && l <= nums.length - 1) {
> 		let a = nums[s]
> 		let b = nums[l]
> 		if (a + b < target) {
> 			l = Math.floor((l + nums.length - 1) / 2);
> 			continue;
> 		} else if (a + b > target) {
> 			s = Math.floor((s + 0) / 2);
> 		} else {
> 			return [a, b]
> 		}
> 	}
> 	throw new Error("没找到")
> }
> ```

二分总体优化不大。。都上排序了 复杂度已经上去了。。

2019-06-04 15:17 UTC, yiqingfeng commented
利用空间换时间：

```javascript
const twoNum = (nums, target) => {
    const maps = {};
    for(let i = 0, len = nums.length; i < len; i++) {
        let diff = target - nums[i];
        if (maps[diff] > -1) {
            return [maps[diff], i];
        }
        maps[nums[i]] = i;
    }
    return [];
}
```

2019-06-05 10:26 UTC, Firenzia commented
function getIndex(src, target){
	let list = [...src].sort(function(a,b){return a-b})

	for(let item of list){
		if(list.indexOf(target-item)!== -1){
			return [list.indexOf(item), list.indexOf(target-item)]
			break
		}
	}
	return []
}
var arr= [2,7,11,15]

getIndex(arr,9) // [0,1]

2019-06-12 08:24 UTC, Izayawww commented
function getIdx(ary, target) {
      let obj = {};
      for (let i = 0; i < ary.length; i++) {
        if (obj[ary[i]]!= undefined) {
          return [obj[ary[i]], i];
        }
        obj[target - ary[i]] = i;
      }
    }

2019-06-14 02:57 UTC, Chelseasc commented
```

function convert(arr, target) {
      for(let i in arr) {
          const test = target - arr[i];
          if(arr.includes(test, i)) {
              return [arr.indexOf(arr[i]), arr.indexOf(test)];
          }
     }
     return '未找到';
}
```

2019-06-14 09:31 UTC, GuoMeng6 commented
> > ```js
> > function sum(arr, target) {
> >   const res = []
> >   for (let i = 0; i < arr.length; i++){
> >     const a = target - arr[i]
> >     const index = arr.indexOf(a,i)
> >     if (index>=0) {
> >       res.push(i, index)
> >     }
> >   }
> >   return res
> > }
> > ```
> > 
> > 
> > _循环一次_
> 
> 当arr = [4, 7, 11, 15], target = 8的时候会有问题，结果是[0, 0]， 显然是有问题的

加个判断
```
function sum2(arr, target) {
  const res = []
  for (let i = 0; i < arr.length; i++){
    const a = target - arr[i]
    const index = arr.indexOf(a,i)
    if (index>=0 && index !==i) { // index 不能等于 i
      res.push(i, index)
    }
  }
  return res
}
```

2019-06-14 09:43 UTC, andyliangshan requested changes
quick

2019-06-18 09:40 UTC, k-0311 commented
const sum = (nums, target) => {
    for (let [index, val] of nums.entries()) {
      let tempIndex = nums.indexOf(target - val)
      if (tempIndex > -1) {
        return [index, tempIndex]
        break
      }
    }
  }

  console.log(sum([2, 11, 15, 7, 9, 8], 23))

2019-07-07 19:11 UTC, Zousdie commented
```
/**
 * @param {number[]} nums
 * @param {number} target
 * @return {number[]}
 */
var twoSum = function(nums, target) {
  if (!Array.isArray(nums) || typeof target !== 'number') {
    return undefined;
  }
  
  var len = nums.length;
  var map = new Map();
  
  for(var i = 0; i < len; i++) {
    const diff = target - nums[i];
    if (map.has(diff)) {
      return [map.get(diff), i];
    }
    
    map.set(nums[i], i);
  }
};
```

2019-07-09 03:49 UTC, Antelopeclouds commented
```
function getSum(arr, tar) {
  let reslut = null
  for (let i = 0; i < arr.length; i++) {
    let temp = tar - arr[i]
    arr.includes(temp) && (reslut = [arr[i], arr[arr.indexOf(tar - arr[i])]])
  }
  return reslut
}
```

2019-07-09 07:08 UTC, 328480460 commented
````
const list = [1, 2, 3, 4, 5, 6, 7, 8];
const target = 13;
const res = [];
for (let i = 0, j = i + 1; i <= list.length;) {
  const start = list[i];
  const end = list[j];
  if (start + end === target) {
    res.push([start, end]);
  }
  j++;
  if (j >= list.length) {
    i++;
    j = i + 1;
  }
}
console.log(res)

2019-07-10 02:01 UTC, Z6T commented
> ```js
> function sum(arr, target) {
>   const res = []
>   for (let i = 0; i < arr.length; i++){
>     const a = target - arr[i]
>     const index = arr.indexOf(a,i)
>     if (index>=0) {
>       res.push(i, index)
>     }
>   }
>   return res
> }
> ```
> 
> _循环一次_

你确定是循环一次吗??? indexOf你以为是怎么实现的呢?

2019-07-12 03:12 UTC, yanzhandong commented
function abb(arr,flag){
	for(let i = 0;i < arr.length;i++){
		let index = arr.indexOf(flag - arr[i]);
		if( index!= -1){
			console.log([i,index])
			break
		}
	}
}
只循环一次  达到目的就break   效率更高

2019-07-12 09:55 UTC, junchaohu commented
```js
const sum2toTarget = (arr, target) => {
    let result = [];
    let len = arr.length;
    for (let i = 0; i< len; i++){
        let tem = target - arr[i];
        if(arr.indexOf(tem) > -1){
            result.push(i, arr.indexOf(tem))
            if( result[0] !== result[1]){
                return result;
            }
        }
    }
    return result;
}

let arr = [2,4,5,1,3,9,8];
let target = 11;
console.log(sum2toTarget(arr,target));
// [0, 5]
```

2019-07-14 15:03 UTC, merged

2019-07-15 06:48 UTC, hehuilin commented
function sumArr (arr, target) {
	if (arr.length < 2) {
		throw new Error('数组长度不能少于2')
	}
	if (arr.length === 2) {
		if (arr[0] + arr[2] === target) {
			return arr
		} else {
			throw new Error('没有符合的数据')
		}
	}
	let restArr = []
	let restObj = {}
	arr.forEach((data, ind) => {
		let rest = target - data
		if (restObj[data] || restObj[data] === 0) {
			restArr = [ind, restObj[data]]
		} else {
			restObj[rest] = ind
		}
	})
	return restArr
}

2019-07-15 08:43 UTC, YufJi commented
```
function twoSum(nums, target) {
   const hash = [];
   const result = [];
   for (let i = 0; i < nums.length; i+=1) {
     const element = nums[i];
     const temp = target - element;
     if(hash[temp] !== undefined) {
       result.push([hash[temp], i]);
     }
     hash[element] = i;
   }
   return result;
}
```

2019-07-15 09:13 UTC, laixiaoyi commented
var arr = [1,2,3,5,6,7,8],target = 9
function func(arr,target) {
	const res = []
	for(let i=0;i<arr.length;i++) {
		const a = target-arr[i]
		if(arr.indexOf(a) > 0) {
			res.push(i,arr.indexOf(a))
			break
		}
	}
	return res
}

2019-07-17 05:51 UTC, yozojo commented
function getComputed(target, array) {
  for (let i = 0; i < array.length; i++) {
    const ele_i = array[i];
    for (let j = i+1; j < array.length; j++) {
      const ele_j = array[j];
      if (target === ele_i + ele_j && ele_i !== ele_j) {
        return [i, j];
      }
    }
  }
  return [];
}

2019-07-17 09:57 UTC, simonjayw commented
`
function towSum (nums, target) {
	const map = {} // 创建一个对象
	for (let i = 0; i < nums.length; i++) {
		const num = nums[i]
		if (map[target - num] != null) { // 判断 map 中是否存在 target - num 的值
			return [target - num, num]
		}
		map[num] = num // 给对象添加的属性，key 即是 value
	}	
}
`

2019-07-17 10:02 UTC, simonjayw commented
```javascript
function twoSum (nums, target) {
	const map = {} // 创建一个对象
	for (let i = 0; i < nums.length; i++) {
		const num = nums[i]
		if (map[target - num] != null) { // 判断 map 中是否存在 target - num 的值
			return [map[target - num], i]
		}
		map[num] = i // 给对象添加的属性，属性为 num，值为 index
	}	
}
```

2019-07-17 11:43 UTC, nuoer2048 commented
let arr=nums.filter(function (v,i) {
    let item = 9-v;
    if(nums.indexOf(item)>=0){
        return v;
    }
})

2019-07-18 06:42 UTC, chenming142 commented
**双循环**
> ```js
> var twoSum = function(nums, target) {
>     const res = []
>     loop:
>     for (let i =0; i<nums.length-1; i++){
>         for (let j = i+1;j<nums.length;j++){
>             if (nums[i]+nums[j]===target){
>                 res.push(i,j)
>                 break loop
>             }
>         }
>     }
>     return res
> };
> ```


**空间换时间**
> ```
> /**
>  * @param {number[]} nums
>  * @param {number} target
>  * @return {number[]}
>  */
> var twoSum = function(nums, target) {
>   if (!Array.isArray(nums) || typeof target !== 'number') {
>     return undefined;
>   }
>   
>   var len = nums.length;
>   var map = new Map();
>   
>   for(var i = 0; i < len; i++) {
>     const diff = target - nums[i];
>     if (map.has(diff)) {
>       return [map.get(diff), i];
>     }
>     
>     map.set(nums[i], i);
>   }
> };
> ```

这两种是正确的，那些使用**indexOf**难道不需要额外的循环么？

2019-07-18 17:39 UTC, YufJi commented
```
  function twosum(arr, sum) {
    const hash = {};
    const result = [];
    for (let i = 0; i < arr.length; i++) {
      const temp = sum - arr[i];
      hash[arr[i]] = i;
      console.log(hash, temp, hash[temp])
      if (hash[temp] !== undefined) {
        result.push([hash[temp], i])
      } 
    }
    return result;
  }
```

2019-07-21 07:29 UTC, yujihu commented
```javascript
function answer(nums, target) {
  for (let i = 0; i < nums.length; i++) {
    for (let j = nums.length - 1; j > i; j--) {
      if (j > i) {
        if (nums[i] + nums[j] === target) {
          return [i, j]
        }
      } else {
        return []
      }
    }
  }
}
```

2019-07-21 07:34 UTC, yujihu commented
```javascript
function answer(nums, target) {
  for (let i = 0; i < nums.length; i++) {
    for (let j = nums.length; j > i; j--) {
      if (nums[i] + nums[j] === target) {
        return [i, j]
      }
    }
  }
}
```

2019-07-22 09:53 UTC, lichenabson commented
经典解法: 双指针
![image](https://user-images.githubusercontent.com/20200267/61623551-6bd3bd80-aca9-11e9-94fc-d4a11cd61731.png)

2019-07-23 08:17 UTC, liuliudaren commented
> ```js
> function sum(arr, target) {
>   const res = []
>   for (let i = 0; i < arr.length; i++){
>     const a = target - arr[i]
>     const index = arr.indexOf(a,i)
>     if (index>=0) {
>       res.push(i, index)
>     }
>   }
>   return res
> }
> ```
> 
> _循环一次_

indexof呢

2019-07-26 02:24 UTC, RYUDEN commented
var twoSum = function(nums, target) {
    const store = {}
    for (let i = 0; i < nums.length; i++) {
        const need = nums[i];
        const needIndex = store[need];
        if (needIndex !== undefined) return [needIndex, i]
        store[target - need] = i;
    }
};
循环一次，定义一个对象，循环数组的时候 数为key ，需要的数为value 。存到对象内，最后找到。可以在循环中把store打印出来观察 store的变化应该很好理解。leetcode第一题

2019-07-26 02:24 UTC, francisXKF commented
> 这样太简单了，直接index解决：
> 
> ```js
> arr.reduce((res, cur, i) => {
> 	const index =  arr.findIndex(x => x === target - cur);
> 	return res || (!!~ index && [i, index])
> }, void 0);
> ```
> 
> 题目可以增加一点难度，找出arr中所有的和为target的元素子集：
> 
> ```js
> function findTarget(arr, target) {
> 	const res = { idx: [], ele: [] };
> 	!function dp(target, index, memoryIndex = [], memoryEle = []) {
> 		const remain = target - arr[index];
> 		if (remain === 0) {
> 			res.idx.push(memoryIndex);
> 			res.ele.push(memoryEle);
> 		}
> 		if (index + 1 >= arr.length) {
> 			return;
> 		}
> 		for (let i = index + 1; i < arr.length; i++ ) {
> 			dp(remain, i, [...memoryIndex, i], [...memoryEle, arr[i]])
> 		}
> 	}(target, 0, [0], [arr[0]]);
> 	return res;
> }
> ```

nums = [2, 5, 5, 7, 11, 15];
target = 10;
不支持这种用例，这种测试用例是否属于合法用例……

2019-07-27 06:54 UTC, azl397985856 commented
这个是 leetcode 原题，由于没有说明是否有序，我们可以采取空间换时间的方式来解决。借助额外的空间完成。

以下是我的参考答案

```js
var twoSum = function(numbers, target) {
    const visited = {} // 记录出现的数字， 空间复杂度N

    for (let index = 0; index < numbers.length; index++) {
        const element = numbers[index];
        if (visited[target - element] !== void 0) {
            return [visited[target - element], index + 1]
        }
        visited[element] = index + 1;   
    }
    return [];
};
```

如果大家对算法感兴趣，欢迎关注我的[leetcode题解](https://github.com/azl397985856/leetcode)

2019-08-01 23:35 UTC, SuAgnes commented
考虑了下重复的问题
`    function sum(arr, target) {
      let _ = [];
      for (let i = 0; i < arr.length; i++) {
        let a = target - arr[i];
        if (arr.includes(a) === true && arr.slice(i, 1).includes(a) === false) {
          _ = [arr.indexOf(a), i]
        }
      }
      return _;
    }

    sum([2, 7, 11, 15], 9)`

2019-08-01 23:36 UTC, SuAgnes commented
考虑了下重复的问题
```JavaScript
 function sum(arr, target) {
let _ = [];
for (let i = 0; i < arr.length; i++) {
let a = target - arr[i];
if (arr.includes(a) === true && arr.slice(i, 1).includes(a) === false) {
_ = [arr.indexOf(a), i]
}
}
return _;
}

sum([2, 7, 11, 15], 9)
```

2019-08-02 00:58 UTC, SuAgnes commented
考虑了重复
```JavaScript
    function sum(arr, target) {
      let _ = [];
      let arr2 = [];
      for (let i = 0; i < arr.length; i++) {
        let a = target - arr[i];
        if (arr.includes(a) === true) {
          arr2.push(a);
          arr2.length !== 1 ? _ = [arr[arr.indexOf(a)], arr[i]] : _ ;
        }
      }
      return _;
    }
```

2019-08-05 15:28 UTC, XNNNN commented
鄙人愚见，
for (let i = 0; i < Arr.length; i++){
	for (let j = i+1; j < Arr.length - i; j++){
		if (Arr[i] + Arr[j] === target) {
			let newArr = []
			newArr.push(Arr[i])
			newArr.push(Arr[j])
			retrun [...new Set(newArr)]
		}
	}
}

2019-08-05 15:29 UTC, XNNNN commented
鄙人愚见
`for (let i = 0; i < Arr.length; i++){
	for (let j = i+1; j < Arr.length - i; j++){
		if (Arr[i] + Arr[j] === target) {
			let newArr = []
			newArr.push(Arr[i])
			newArr.push(Arr[j])
			retrun [...new Set(newArr)]
		}
	}
}`

2019-08-07 09:43 UTC, jwei921118 commented
### 一次循环通过indexOf查找
``` code
let nums = [2, 7, 11, 15];

function findTarget(arr, target) {
    let len = arr.length;
    if (len < 2) {
        return '至少提供两个数字';
    }
    let inx = 0;
    let endx;
    while (inx < len) {
        endx = arr.indexOf(target - [arr[inx]])
        if (endx > -1 && endx !== inx) {
            break;
        }
        inx++;
    }
    return endx > -1 ? [inx, endx] : '404 not found';
}

let s = findTarget(nums, 13);
```

2019-08-08 09:22 UTC, yuganzigogo commented
```
let nums = [2, 7, 11, 15]
    const train = (nums, target) => {
      let map = nums.reduce((init, value, index) => (init[value] = index, init), {})
      let arr = []
      nums.forEach((item, index) => {
        let num = target - item
        if(num in map) {
          arr = [map[num], index]
        }
      })
      return [...new Set(arr)]
    }
    console.log(train(nums,22))
```

2019-08-08 14:37 UTC, wjjhhh commented
// 双指针
function func(arr, target) {
  let index = 0, lastIndex = arr.length - 1
  while (index <= lastIndex) {
    let _res = arr[index] + arr[lastIndex]
    if (_res === target) {
      return [index, lastIndex]
    }
    else if (_res < target) {
      index++
    } else {
      lastIndex--
    }
  }
  throw new Error('no result')
}
console.log(func([2, 7, 11, 15], 9))

2019-08-09 01:51 UTC, lichenabson commented
> // 双指针
> function func(arr, target) {
> let index = 0, lastIndex = arr.length - 1
> while (index <= lastIndex) {
> let _res = arr[index] + arr[lastIndex]
> if (_res === target) {
> return [index, lastIndex]
> }
> else if (_res < target) {
> index++
> } else {
> lastIndex--
> }
> }
> throw new Error('no result')
> }
> console.log(func([2, 7, 11, 15], 9))

双指针不用先排序的吗? 可能是个无序数组

2019-08-09 01:54 UTC, wjjhhh commented
> > // 双指针
> > function func(arr, target) {
> > let index = 0, lastIndex = arr.length - 1
> > while (index <= lastIndex) {
> > let _res = arr[index] + arr[lastIndex]
> > if (_res === target) {
> > return [index, lastIndex]
> > }
> > else if (_res < target) {
> > index++
> > } else {
> > lastIndex--
> > }
> > }
> > throw new Error('no result')
> > }
> > console.log(func([2, 7, 11, 15], 9))
> 
> 双指针不用先排序的吗? 可能是个无序数组

是的老铁，刚想起漏了先排序

2019-08-13 01:55 UTC, 0425liu commented
const traget = (arr, result) => {
    for (let i = 0, l = arr.length; i < l; i++) {
      for (let j = i; j < l; j++) {
        if ((arr[i] + arr[j]) === result) {
          return [i, j]
        }
      }
    }
  }

2019-08-13 02:19 UTC, helloyoucan commented
```javascript
//1.
const nums  = [11,5,1,4,8,9,15];
const TARGET = 14;
let results = [];
for(let i=0,l=nums.length;i<l-1;i++){
	for(let j=i+1;j<l;j++){
		if(nums[i]<TARGET&&(nums[i]+nums[j])===TARGET){
			results = [nums[i],nums[j]]
			break;
		}
	}
	if(results.length===2){
		break;
	}
}
console.log(results)
```
```javascript
//2.
const nums  = [11,5,1,4,8,9,15];
const TARGET = 14;
const maps = {};
let results = [];
for(let i=0,l=nums.length;i<l-1;i++){
	if(nums[i]<TARGET){
		maps[TARGET-nums[i]] = i
		if(maps[nums[i]]!==undefined){
			results = [TARGET-nums[i],nums[i]]
			break;
		}
	}
	if(results.length===2){
		break;
	}
}
console.log(results)
```

2019-08-14 11:03 UTC, yangxinSamsara commented
> ```js
> function anwser (arr, target) {
>   let map = {}
>   for (let i = 0; i < arr.length; i++) {
>     map[arr[i]] = i
>   }
>   for (let i = 0; i < arr.length; i++) {
>     var d = target - arr[i]
>     if (map[d]) {
>       return [i, map[d]]
>     }
>   }
>   return new Error('404 not found')
> }
> ```

![image](https://user-images.githubusercontent.com/31761016/63016398-29775800-bec6-11e9-8945-d91ff1adfe80.png)

2019-08-16 08:45 UTC, xing-zlear commented
```javascript
function sum(nums, target) {
	if(nums.length === 0) {
		return []
	}
	var arr = []
	nums.map((num, index) => {
		arr[num] = index
	})
	for(let i = 0, leni = nums.length; i < leni; i++){
		if(arr[target - nums[i]]) {
			return [i, arr[target - nums[i]]]
		}
	}
	return []
}
```

2019-08-18 13:29 UTC, liuxingit commented
function fun(arr, sum){
  for(let i = 0; i < arr.length; i++){
    let value = arr[i];
    if(value < sum){
      let index = arr.indexOf(sum - value)
      if(index > -1){
        return [i, index]
      }
    } 
  }
  return [];
}
fun([2,7,11,15], 9)

2019-08-19 14:56 UTC, yft commented
```js
function test (arr, target) {
    let i, v, s;
    let total = arr.length;
    let searching = Object.create(null);
    for (i = 0; i < i < total; i++) {
        v = arr[i];
        s = searching[v];
        if (s === undefined) { // 如果 v 的小伙伴没找到他，他就登记寻人启事寻找小伙伴
            if (searching[target - v] === undefined) {
                searching[target - v] = i;
            }
        } else return [s, i]; // 找到了
    }
    return null;
}

let nums = [11, 2, 7, 11, 15, -1], target = 14;
console.log(test(nums, target));
```

2019-08-20 11:28 UTC, zjkblade commented
```
    let arr = [11, 1, 5, 2, 3, 7, 15];
    let target = 10;

    let test = (arr, target) => {
        let map = {};
        for (let i = 0, length = arr.length; i < length; i++) {
            if (map[arr[i]] === undefined) {
                map[arr[i]] = i;
            }
        }
        for (let i = 0, length = arr.length; i < length; i++) {
            let j = map[target - arr[i]];
            if (j && j >= 0 && i !== j) {
                return [i, j];
            }
        }
        return -1;
    };

    console.log(test(arr, target));
```

2019-08-20 11:30 UTC, zjkblade commented
```
    let arr = [11, 1, 5, 2, 3, 7, 15];
    let target = 10;

    let test = (arr, target) => {
        let map = {};
        for (let i = 0, length = arr.length; i < length; i++) {
            if (map[arr[i]] === undefined) {
                map[arr[i]] = i;
            }
        }
        for (let i = 0, length = arr.length; i < length; i++) {
            let j = map[target - arr[i]];
            if (j > i) {
                return [i, j];
            }
        }
        return -1;
    };

    console.log(test(arr, target));
```

2019-08-23 11:01 UTC, lcny0606 commented
> ```js
> function sum(arr, target) {
>   const res = []
>   for (let i = 0; i < arr.length; i++){
>     const a = target - arr[i]
>     const index = arr.indexOf(a,i)
>     if (index>=0) {
>       res.push(i, index)
>     }
>   }
>   return res
> }
> ```
> 
> _循环一次_

这个没有去除自身

2019-08-28 09:30 UTC, usherwong commented
大部分时间复杂度为O(n^2)，可以优化下，思路
1.  排序Sort默认快速排序，时间复杂度为O(nlogn)，排序为从小到大
2.  排好序之后用双指针，i，j，指向数组第一个及最后一个元素
3.  两个元素的和如果小于target，左侧指针右移。否则右侧指针左移动。时间复杂度为O(n)
总的时间复杂度为Max(O(nlogn), O(n))=O(nlogn)
代码如下
```javascript
function arraySumTarget() {
    let [arr, target] = arguments

    function sortFunc(i, j) {
        if (i < j) {
            return -1
        } else {
            return 1
        }
    }
    let s = arr.sort(sortFunc)
    let i = 0
    let j = s.length
    while (i < j) {
        if (s[i] + s[j] === target) {
            return {
                startIndex: i,
                endIndex: j
            }
        } else if (s[i] + s[j] < target) {
            i = i + 1
        } else {
            j = j - 1
        }
    }
    return -1
}

```

2019-08-31 14:53 UTC, yuwanli commented
> ```js
> function sum(arr, target) {
>   const res = []
>   for (let i = 0; i < arr.length; i++){
>     const a = target - arr[i]
>     const index = arr.indexOf(a,i)
>     if (index>=0) {
>       res.push(i, index)
>     }
>   }
>   return res
> }
> ```

有点小问题，注意审题
```js
sum([5,6,7,8],10)// [0,0]
```

```js
(index>=0 && index !== i)
```

2019-09-01 10:00 UTC, liuxingit commented
thanks

2019-09-08 10:41 UTC, CanUlook commented
`/**
 * 给定 nums = [2, 7, 11, 15], target = 9
 * 因为 nums[0] + nums[1] = 2 + 7 = 9
 * 所以返回 [0, 1]
 */

var array = [2, 7, 11, 15]
var target = 10
function addNum (array, target) {
    for (var i = 0; i < array.length; i++) {
        var index = array.indexOf(target-array[i])
        if (index > -1 && index != i) {
            return [i, index]
        }
    }
    return 'no that array'
}
console.log(addNum (array, target))`

2019-09-11 08:20 UTC, wisenchen commented
`   
   var map = {};
   for(var i = 0, len = nums.length; i < len; i++){
       let n = target-nums[i];
       if(map[nums[i]] !== undefined){
           return [map[nums[i]],i]
       }
       map[n] = i;
   } 
    return [];
`

2019-09-17 02:06 UTC, yaodongyi commented
```javascript
/**
 * 生成随机nums
 * @param {Number} min 最小值，最小长度
 * @param {Number} max 最大值，最大长度
 */
let nums = function (min, max) {
    let len = Math.floor(Math.random() * (max - min)) + min, arr = [];
    while (len) {
        len--;
        arr.push(Math.floor(Math.random() * (max - min)) + min)
    };
    return [...new Set(arr)].sort((x, y) => x - y);
};
const target = 9; // 设定目标值
let arr = [];
/**
 * 查询累加为目标值的两个数
 * @param {Array} nums 
 * @param {Number} target 
 */
function searchAccumulator(nums, target) {
    for (let i = 0; i < nums.length; i++) {
        for (let j = nums.length - 1; j > i; j--) {
            if (nums[i] + nums[j] === target) {
                // return [nums[i], nums[j]]  // 如果只查询出一个中和为目标值的两个数
                arr.push([nums[i], nums[j]]); // 查询出所有中和为目标值的两个数
            }
        };
    };
    return arr.length === 0 ? "未查询到数组中和为目标值的两个数。" : arr;
};
console.log(searchAccumulator(nums(1, 10), target));
```

2019-09-22 06:33 UTC, fengshenhai-0727 commented
```javascript
/*

给定一个整数数组和一个目标值，找出数组中和为目标值的两个数。

你可以假设每个输入只对应一种答案，且同样的元素不能被重复利用。

示例：

给定 nums = [2, 7, 11, 15], target = 9

因为 nums[0] + nums[1] = 2 + 7 = 9
所以返回 [0, 1]

*/

function twoSum(arr,target){
    const map = {};
    for(let i=0;i<arr.length;i++){
        if(map[target-arr[i]]!==undefined){
            return [map[target-arr[i]],i];
        }else{
            map[arr[i]] = i;
        }
    }
    return [];
}

const nums = [2,7,11,15]
console.log(twoSum(nums,17))
```

2019-09-25 16:28 UTC, chaijinsong commented
**方法1**
思路：双层遍历，双层遍历，每次遍历都是第 i 个 和后 n-i 中的每一个做加法，如果符合条件，直接return
时间复杂度：
当 i = 0 第二重循环需要执行 (n - 1)次
当 i = 1 第二重循环需要执行 (n - 2)次
当 i = 2 第二重循环需要执行 (n - 3)次
.....
得到最终执行的次数为 (n-1) + (n-2) + (n-3) +... + 0
((n-1) + 0) * n / 2 = (n^2 -n) / 2 = O(n^2)
```
const twoSum = function (numbers, target) {
    let result = [];
    let len = numbers.length;
    for (let i = 0; i < len; i++) {
        for(let j = i+1; j < len; j++) {
            if (numbers[i] + numbers[j] === target) {
                result = [i, j];
                break;
            }
        }
    }
    return result;
}
```

**方法2**
```js
const twoSum = function (numbers, target) {
   let hashMap = {};
   for (let i = 0; i < numbers.length; i++) {
     let value = numbers[i];
		 // 如果 map 中存在 这个key值，说明 nums[i] + key = target; 所以就是找到了
     if (hashMap[value] !== undefined) {
         return [hashMap[value], i];
     }
		 // 将 target - nums[i] 作为key，当前下标作为value存储在map中
     hashMap[target - value] = i;
   }
}
```
时间复杂度:
只有一次循环，所以时间复杂度为 O(n)

2019-10-10 03:35 UTC, xuanxia commented
业务中遇到过更复杂的( 有一堆商品， 用户输入预算， 根据用户的预算找出最接近的商品组合 )。   给定一个数组 和 一个目标值，找出数组中和为目标值或最接近目标值的N个数，且同样的元素不能被重复利用 会有M种方案，求这M种组合。 使用 01背包算法解决。

2019-10-13 14:10 UTC, ToneNonly commented
function findMembers(arr, sum) {
    var need = []
    var result = '没找到，瞎忙活'
    arr.forEach((val) => {
        if (val < sum && need.indexOf(val) < 0) {
            need.push(sum - val)
        } else if (need.indexOf(val) >= 0) {
            result = [sum - val, val]
            return;
        }
    })
    return result;
}

console.log(findMembers([2, 10, 7, 3], 17));

2019-10-13 14:10 UTC, ToneNonly commented
`function findMembers(arr, sum) {
    var need = []
    var result = '没找到，瞎忙活'
    arr.forEach((val) => {
        if (val < sum && need.indexOf(val) < 0) {
            need.push(sum - val)
        } else if (need.indexOf(val) >= 0) {
            result = [sum - val, val]
            return;
        }
    })
    return result;
}

console.log(findMembers([2, 10, 7, 3], 17));
`

2019-10-15 09:09 UTC, HbuJiaTian commented
function add(nums, target){
    let length = nums.length;
    for(let i = 0; i < length; i++){
        let j = i +1;
        while(j < length){
            if(nums[i] + nums[j] === target){
                return [i, j]
            }
            j++;
        }
    }
    return null;
}

2019-10-19 09:41 UTC, aeolusheath commented
这是leetcode的第一道题：

```javascript

  function twoSum(nums, target) {
      let map = new Map()
      for (let i = 0; i < nums.length; i++) {
        let remain = target - nums[i]
        if (map.has(remain) && i !== map.get(remain)) {
          return [map.get(remain), i]
        }
        map.set(nums[i], i) //放在后面是因为前面要判断i !== map.get(remain), 考虑 [3, 2, 4], 6的情况
      }
    }


```

2019-10-21 03:33 UTC, 307590317 commented
```javascript
//咱不考虑indexOf兼容问题
function sum(ary,tar) {
  for (let i = 0; i < ary.length; i++) {
    let num2 = tar - ary[i];
    let num2I = ary.indexOf(num2,i+1);
    if(num2I > -1) return [i,num2I];
  }
  return [];
}
let nums = [3, 3, 4, 2], target = 6;
console.log(sum(nums, target)); //[0, 1]
```
欢迎交流

2019-10-22 03:50 UTC, Tsingwu commented
`let nums = [2, 7, 11, 15];
  let target = 9;
  function filter(nums, target) {
    let arr = [];
	  for (let i = 0; i < nums.length; i++) {
	    if (nums.indexOf(target - nums[i]) !== -1){
		    arr[0] = i;
	      arr[1] = nums.indexOf(target - nums[i]);
	      break;
	    }
	  }
	  return arr;
  }
  let result = filter(nums, target);
  console.log(result);
  console.log(nums[result[0]] + nums[result[1]] === target);`

2019-10-24 09:25 UTC, JackFGreen commented
function find (arr, n) {
  // arr  [2, 7, 9, 11, 3, 15, 0]
  // arr  [2, 7, 9, 3, 0]
  // diff [7, 2, 0, 6, 9]
  const diff = arr.map(i => {
    if (i <= n) {
      return n - i
    } else {
      arr.splice(i, 1)
    }
  })
  // arr & diff 交集
  const res = arr.filter(i => diff.includes(i))
  console.log(res)
}

const data = [2, 7, 9, 11, 3, 15, 0]
const target = 9
find(data, target)
// [ 2, 7, 9, 0 ]

2019-11-01 04:27 UTC, lalalaxx commented
```
function fn(nums,target){
    let arr = [...new Set(nums)],result = [];
    arr.filter((item,index) => {
	if(arr.indexOf(target - item) !== -1){
	    result = [arr.indexOf(item),arr.indexOf(target - item)].sort((a,b) => a - b)
	}
    })
    return result

}
fn([2, 7, 11, 15],9)
```

2019-11-02 11:45 UTC, Fzzzzy commented
```js
function find(arr, target) {
    let obj = {};
    arr.map((item, idx) => {
        obj[item] = idx;
    });

    for (let key in obj) {
        let remain = target - key;
        if (obj[remain] && obj[remain] != obj[key]) return [obj[key], obj[remain]];
    }
    return null;
}
```

2019-11-03 13:59 UTC, pjf0803 commented
let t = (a, b) => {
  return b.filter(e => b.filter(o => o + e === a).length > 0)
}
const nums = [2, 7, 11, 15], target = 9 ;
console.log(t(target, nums), 144)

2019-11-08 09:33 UTC, DavidChen93 commented
暴力不可取，时间复杂度O(n^2)
使用双指针，时间复杂度O(n)
function func (arr, num) {
  if (arr.length < 2 || num < 2) return 'error'
  let i = 0, // 头指针
      j = arr.length - 1 // 尾指针
  while(i < j) {
    if (arr[i] + arr[j] < num) {
      ++i
    } else if (arr[i] + arr[j] > num) {
      --j
    } else {
      return [arr[i], arr[j]]
    }
  }
  return '404 Not Found'
}

console.log(func([1,2, 7, 11, 15], 9)) // [ 2, 7 ]

2019-11-11 05:59 UTC, huangjieqiu commented
function sum(arr, target) {
        for (var i = 0; i < arr.length; i++) {
            var diff = target - arr[i]
            var index = arr.indexOf(diff)
            if (index > -1) {
                return [i, index]
            }
        }
        return []
    }

2019-11-11 11:46 UTC, zhuogx commented
> ```js
> function sum(arr, target) {
>   const res = []
>   for (let i = 0; i < arr.length; i++){
>     const a = target - arr[i]
>     const index = arr.indexOf(a,i)
>     if (index>=0) {
>       res.push(i, index)
>     }
>   }
>   return res
> }
> ```
> 
> _循环一次_

indexOf本身也是一次循环

2019-11-11 11:50 UTC, zhuogx commented
> ```js
> function anwser (arr, target) {
>   let map = {}
>   for (let i = 0; i < arr.length; i++) {
>     map[arr[i]] = i
>   }
>   for (let i = 0; i < arr.length; i++) {
>     var d = target - arr[i]
>     if (map[d]) {
>       return [i, map[d]]
>     }
>   }
>   return new Error('404 not found')
> }
> ```

再判断一下俩个下标不相等，是不是更好
if (map[d] && i != map[d]) {
  return [i, map[d]]
}

2019-11-17 14:14 UTC, huangpb commented
> ```js
> function anwser (arr, target) {
>   let map = {}
>   for (let i = 0; i < arr.length; i++) {
>     map[arr[i]] = i
>   }
>   for (let i = 0; i < arr.length; i++) {
>     var d = target - arr[i]
>     if (map[d]) {
>       return [i, map[d]]
>     }
>   }
>   return new Error('404 not found')
> }
> ```

[2,2,3] 4，你用这个去执行一下你的函数试试

2019-11-17 14:18 UTC, huangpb commented
> ```js
> function sum(arr, target) {
>   const res = []
>   for (let i = 0; i < arr.length; i++){
>     const a = target - arr[i]
>     const index = arr.indexOf(a,i)
>     if (index>=0) {
>       res.push(i, index)
>     }
>   }
>   return res
> }
> ```
> 
> _循环一次_

匹配到了直接在循环里 return 就好了，没必要在循环后面的数了

2019-11-26 08:51 UTC, Jmingzi commented
```js
function two(nums, target) {
  let tmp;
  for (let i = 0; i < nums.length; i++) {
    if (i < target) {
      tmp = nums[i];
      for (let j = i + 1; j < nums.length; j++) {
        if (tmp + nums[j] === target) {
          console.log([i, j]);
          return;
        }
      }
    }
  }
}
```

2019-12-20 17:36 UTC, ricenoddle commented
function addNum(arr, target){
    var result = [];
    for(let i = 0; i < arr.length; i ++){
        if(arr.indexOf(target - arr[i]) !== -1){
            result.push(i);
            result.push(arr.indexOf(target - arr[i]));
            return result;
        }
    }
    return -1;
}

2019-12-27 08:34 UTC, 1993klk commented
@DavidChen93 
一样的想法，可以增加判断一下首尾相加如果大于预期值，就可以直接return了

2020-01-02 06:34 UTC, cpg0525 commented
> ```js
> function anwser (arr, target) {
>   let map = {}
>   for (let i = 0; i < arr.length; i++) {
>     map[arr[i]] = i
>   }
>   for (let i = 0; i < arr.length; i++) {
>     var d = target - arr[i]
>     if (map[d]) {
>       return [i, map[d]]
>     }
>   }
>   return new Error('404 not found')
> }
> ```

anwser([1,3,4,2],6) 
期望 [2, 3];
输出 [1, 1];

2020-01-02 07:08 UTC, cpg0525 commented
> > ```js
> > function sum(arr, target) {
> >   const res = []
> >   for (let i = 0; i < arr.length; i++){
> >     const a = target - arr[i]
> >     const index = arr.indexOf(a,i)
> >     if (index>=0) {
> >       res.push(i, index)
> >     }
> >   }
> >   return res
> > }
> > ```
> > 
> > 
> > _循环一次_
> 
> 匹配到了直接在循环里 return 就好了，没必要在循环后面的数了

sum([3,2,4], 6)
期望 [1, 2];
输出 [0, 0, 1, 2];

2020-01-21 05:35 UTC, SSSSSFFFFF commented
```
function addTwoNum(arr,num,index =0){
    let secIndex = 0
    recursion()
    function recursion(){
        if (arr[index] <= num) {
            if (arr[index] == num - arr[secIndex] && index != secIndex) {
                console.log(new Array(index, secIndex))
            } else {
                secIndex++
                if (secIndex < arr.length){
                    recursion()
                } else {
                    index++
                    if (index < arr.length){
                        addTwoNum(arr, num, index)
                    }
                }
            }
        }
    }
}
addTwoNum([2, 7, 11, 15],22) //[1,3]
```

2020-02-05 03:29 UTC, zhuxinyu-znb commented
```
/**
 * @param {number[]} nums
 * @param {number} target
 * @return {number[]}
 */
var twoSum = function(nums, target) {
    if(!nums || nums.length === 0) {
        return null;
    }
    let res = {};
    for(let i = 0, len = nums.length; i < len; i++) {
        if(res[nums[i]] || res[nums[i]] === 0) {
            return [res[nums[i]], i];
        }
        let diff = target - nums[i];
        res[diff] = i;
    }

    return null;
};
```

2020-02-05 14:09 UTC, wendyjw commented
只能想到比较复杂的对比方法，可以获取所有的组合形式

     var num = [2, 7, 11, 15, 3, 16]
     var target = 18
     var objArr = []
     for (let i = 0; i < num.length; i++) {
          for (let j = num.length - 1; j > i; j--) {
               if (num[i] + num[j] === target) {
                   objArr.push({k1: i, k2: j})
               }
          } 
     }

objArr 为：[ {k1: 0, k2: 5}, {k1: 1, k2: 2}, {k1: 3, k2: 4} ]
数组中显示了所有组合形式，其中k1, k2是数组元素下标

2020-02-06 10:53 UTC, tywei90 commented
只循环一次数组就找到所有组合，这样时间复杂度就是 O(N)。用两个指针 i 和 j，各自指向数组的首尾两端，令 i = 0，j = n - 1，然后 i++，j--，逐次判断 a[i] + a[j] === sum。

```js
const arr = [1,2,4,6,7,9,10]
const sum = 8

function twoSum (arr, sum) {
  const result = []
  let i = 0
      j = arr.length - 1
  
  while (i < j) {
    if (arr[i] + arr[j] > sum) {
      j--
    } else if (arr[i] + arr[j] < sum) {
      i++
    } else {
      result.push([arr[i], arr[j]])
      i++
      j--
    }
  }
  return result
}

twoSum(arr, sum)
```

2020-03-09 06:39 UTC, doudouaaa commented
````
function g(arr, target) {
	let map = {};
	for(let i = 0, len = arr.length; i < len; i++) {
		let num = arr[i];
		let dif = target - num;
		if(map[dif] !== undefined) {
			return [map[dif], i]
		}
		map[num] = i;
	}
	return '404'
}
````

2020-03-09 06:42 UTC, doudouaaa commented
````
function g(arr, target) {
	let map = {};
	for(let i = 0, len = arr.length; i < len; i++) {
		let num = arr[i];
		let dif = target - num;
		if(map[dif] !== undefined) {
			return [map[dif], i]
		}
		map[num] = i;
	}
	return '404'
}
````

2020-03-27 08:32 UTC, litokele2018 commented
```js
function sum(nums, target) {
  let map = new Map()

  for (let i in nums) {
    map.set(nums[i], i)
  }
  for (let i = 0, length = nums.length; i < length; i ++) {
    let s = target - nums[i]
    if (map.has(s) && map.get(s) !== i.toString()) {
      return [i, parseInt(map.get(s))].sort((a, b) => {return a - b})
    }
  }
  return false
}
```

2020-04-02 09:30 UTC, JiangMengLei commented
> > ```js
> > function sum(arr, target) {
> >   const res = []
> >   for (let i = 0; i < arr.length; i++){
> >     const a = target - arr[i]
> >     const index = arr.indexOf(a,i)
> >     if (index>=0) {
> >       res.push(i, index)
> >     }
> >   }
> >   return res
> > }
> > ```
> > 
> > 
> > _循环一次_
> 
> indexOf本身也是一次循环

确实这样

2020-04-10 07:00 UTC, GTRgoSky commented
// 给定一个整数数组和一个目标值，找出数组中和为目标值的两个数。
// 你可以假设每个输入只对应一种答案，且同样的元素不能被重复利用。
function t(arr, t) {
	if (arr.length < 2) throw new Error('数组长度需要大于2');
	function _t(arr, t, s = 0, em = []) {
		let _arr = [...arr];
		let n = _arr[s];
		let _em = [...em];
		if (s > _arr.length - 1) return _em;
		if (isNaN(n)) {
			s++;
			return _t(_arr, t, s, _em);
		}
		for (let i = s + 1; i < _arr.length; i++) {
			let is = _arr[i];
			if (is + n == t) {
				_em.push(s, i);
				_arr.splice(s, 1, undefined);
				_arr.splice(i, 1, undefined);
				break;
			}
		}
		s++;
		return _t(_arr, t, s, _em);
	}
	return _t(arr, t, 0, []);
}

t([2, 7, 11, 15, 1, 8, 2, 7, 2, 9, 0], 9) //=> [0, 1, 4, 5, 6, 7, 9, 10]

2020-04-22 14:30 UTC, xiaochen-01 commented
```
function getTwoNum (nums, target) {
        let add1, add2, surplus = [];
        for(let i of nums.keys()) {
            add1 = nums[i];
            add2 = target - add1;
            surplus = nums.slice(i + 1)
            if(nums.includes(add2)) {
                return [i, nums.indexOf(add2)]
            }
        }
        return '没有找到。。。'
    }

    console.log(getTwoNum([2, 7, 11, 15], 27))
```

2020-04-23 03:16 UTC, coveyz commented
嘻嘻 一个小循环就解决了
```
const sumofNumber = (arr,target) => {
  for (let index = 0; index < arr.length; index++) {
    const element = arr[index]
    const aim = target - element
    if (arr.includes(aim)) {
      return [index,arr.indexOf(aim)]
    }
  }
}
```

2020-04-23 03:18 UTC, coveyz commented
🔫嘻嘻
```
const sumofNumber = (arr,target) => {
  for (let index = 0; index < arr.length; index++) {
    const element = arr[index]
    const aim = target - element
    if (arr.includes(aim) && aim !== element) {
      return [index,arr.indexOf(aim)]
    }
  }
}
```

2020-05-06 11:32 UTC, tangzhibao commented
```javascript
const nums = Array(100).fill(0).map((c,i) => i+1).sort(() => Math.random()-0.5)
console.log(nums)  // 1-100乱序整数组

const target = Math.floor(Math.random()*100)
console.log(target)  // 随机目标

function filter(num, arr) {
  let temp = arr.filter(item => item <= num)  // 过滤不可能项
  let res = []

  while(temp.length) {
    const a = temp.pop()  // 变相去除已使用元素
    if (!a) continue
    const bIndex = temp.findIndex(item => item === num - a)  // 无论indexOf还是findIndex都进行了二次遍历，不要用includes，否则会多一次遍历去查找元素
    if (bIndex === -1) continue
    const b = temp[bIndex]
    temp[bIndex] = null  // 变相去除已使用元素
    res.push([a, b])
  }
  return res
}

console.log(filter(target, nums))
```

![微信截图_20200506193207](https://user-images.githubusercontent.com/47908524/81172151-4b72b680-8fd0-11ea-8ac8-a1e5e87d163a.png)

2020-05-13 13:36 UTC, lqk9511 commented
``` js
/**
 * @param {number[]} nums
 * @param {number} target
 * @return {number[]}
 */
var twoSum = function (nums, target) {
  let _map = new Map()
  for (let i = 0; i < nums.length; i++) {
    const _temp = nums[i] - target
    if (_map.has(_temp)) return [_map.get(_temp), i]
    _map.set(_temp, i)
  }
}

```

2020-05-19 08:58 UTC, liuwenai commented
```js
function sum(arr, target) {
    const res = []
    for (let i = 0; i < arr.length; i++) {
       for(let j = i+1;j < arr.length;j ++){
           if(arr[i] +  arr[j] === target){
               res.push(i,j);
           }
       }
    }
    return res
}

console.log(sum([6, 2, 15], 9))

```

2020-05-28 09:56 UTC, zhangpanfei commented
```js
function sum(arr, target) {
  const res = [];
  const already = [];
  for (let i = 0; i < arr.length; i++) {
    const diffVal = target - arr[i];
    for (let j = 0; j < arr.length; j++) {
      if (arr[j] === diffVal) {
        if (
          i !== j &&
          already.indexOf(i) === -1 &&
          already.indexOf(j) === -1
        ) {
          res.push([i, j]);
          already.push(i, j);
        }
      }
    }
  }
  return res;
}
```

2020-06-11 13:04 UTC, Hanzc-hl commented
```js
// 需要用到求交集的思路
function intersect(a, b) {
  let map = {}
  let result = []
  for (let aa of a) {
    if (map[aa]) {
      map[aa]++
    } else {
      map[aa] = 1
    }
  }
  for (let bb of b) {
    if (map[bb]) {
      result.push(bb)
    }
  }
  return result
}

let target = 9
let nums = [2, 7, 11, 15]
// 要求和为target (t), 假设x+y = t, 则y = t - x;  x = t - y; 
let nums1 = nums.map((item) => target - item)

let result = intersect(nums, nums1)
console.log(result)
```

2020-06-18 09:30 UTC, jackchang2015 commented
> > > ```js
> > > function sum(arr, target) {
> > >   const res = []
> > >   for (let i = 0; i < arr.length; i++){
> > >     const a = target - arr[i]
> > >     const index = arr.indexOf(a,i)
> > >     if (index>=0) {
> > >       res.push(i, index)
> > >     }
> > >   }
> > >   return res
> > > }
> > > ```
> > > 
> > > 
> > > _循环一次_
> > 
> > 
> > 当arr = [4, 7, 11, 15], target = 8的时候会有问题，结果是[0, 0]， 显然是有问题的
> 
> 加个判断
> 
> ```
> function sum(arr, target) {
>   const res = []
>   for (let i = 0; i < arr.length; i++){
>     const a = target - arr[i]
>     const index = arr.indexOf(a,i)
>     if (index>=0 && index !==i) { // index 不能等于 i
>       res.push(i, index)
>     }
>   }
>   return res
> }
> ```

[4, 4, 11, 15] , 8  这个还是有问题

2020-07-03 08:59 UTC, yuanxiang1990 commented
```
function searchTotalIndex(array, target) {
  const res = [];
  if (array.length < 2) {
    return res;
  }
  array = array.map((item, i) => {
    return {
      index: i,
      val: item
    }
  });
  array.sort((a, b) => a.val - b.val);
  let i = 0, j = array.length - 1;
  while (i !== j) {
    if (array[i].val + array[j].val === target) {
      res.push([array[i].index, array[j].index]);
      break
    } else if (array[i].val + array[j].val > target) {
      j--;
    } else {
      i++;
    }
  }
  return res;
}

let nums = [4, 4, 11, 15] , target = 8;
console.log(searchTotalIndex(nums, target))

2020-07-04 02:53 UTC, justsoup commented
`		var nums=[1,2,8,11,15,21],target=29;

		function check(newNums,target){
			if(!isArray(newNums)) return;
			if(newNums.length<2) return;

			while(newNums.length!==0){
				let temp=newNums.shift(newNums[0]);
				for(var i=0;i<newNums.length;i++){
					if(newNums[i]+temp===target){
						return [temp,newNums[i]];
					}
				}
			}
		}
		console.log(check(nums,target));`

2020-07-04 08:52 UTC, fengzi91 commented
```
const add = (arr, target) => {
    const result = []
    arr.some((item, index) => arr.some((i, _index) => i + item === target && index !== _index ? result.push(index, _index) : false))
    return result;
}
```

2020-07-08 08:53 UTC, 523451928 commented
```
const nums = [2, 7, 11, 15]
function genarateArr(nums, arr = []) {
  const start = nums.shift()
  for (let i = 0; i < nums.length; i++) {
    arr.push([start, nums[i]])
  }
  if (nums.length > 1) {
    arr.concat(genarateArr(nums, arr))
  }
  return arr
}
function getIndex(nums, target) {
  const numbers = [...nums]
  const arrs = genarateArr(numbers)
  let currentArr = []
  arrs.forEach((arr) => {
    if (arr[0] + arr[1] === target) {
      currentArr = arr
      return
    }
  })
  return currentArr.map(item => nums.indexOf(item))
}
getIndex(nums, 13)
```

2020-07-10 15:39 UTC, handsomeguyyangchao commented
`function find(nums,target){
    var map = new Map();
    for(var i = 0;i<nums.length;i++){
        var k = target - nums[i]; // nums[i] k
        map.set(k,i);
        if(map.has(nums[i])){
             return [map.get(nums[i]),i]   
        }
        
    }
    return []
}
var nums = [2, 7, 11, 15],target = 9
find(nums,target)`

2020-07-10 15:54 UTC, handsomeguyyangchao commented
```
function find(nums,target){ // O(n) 
    var map = new Map();
    for(var i = 0;i<nums.length;i++){
        var k = target - nums[i]; 
        map.set(k,i); // 先将反数存起来，如果将来遍历到了这个数，就说明存在
        if(map.has(nums[i])){
             return [map.get(nums[i]),i]   // map.get(nums[i]) 拿到的是反数的index，i是当前数便利的数的index
        }
    }
    return []
}
var nums = [2, 7, 11, 15],target = 9
find(nums,target)
```

2020-07-17 08:02 UTC, superyang325 commented
```
时间复杂度 O(n) 
function find(nums,target){ 
    var map = new Map();
    for(var i = 0,len = nums.length;i<len;i++){
        if(map.has(nums[i])){
             return [map.get(nums[i]),i]   // map.get(nums[i]) 拿到的是反数的index，i是当前数便利的数的index
        }
        var k = target - nums[i]; 
        map.set(k,i); // 先将反数存起来，如果将来遍历到了这个数，就说明存在
        
    }
    return []
}
find([2, 7, 11, 15],9)
```

2020-07-18 06:27 UTC, Ljunyu commented
//根据上面老哥的改了下
  function anwser(arr, target) {
    let map = {}
    for (let i = 0; i < arr.length; i++) {
      map[i] = arr[i]
    }
    console.log(map)
    console.log(1, arr)
    for (let i = 0; i < arr.length; i++) {
      var d = target - arr[i]
      if (map[i] == target - d && typeof map[d] !== 'undefined') {
        return [map[i], target - arr[i]]
      }
    }
    return new Error('404 not found')
  }

2020-07-21 13:43 UTC, zengkaiz commented
```javascript
function(nums, target) {
    let newMap = new Map()
    for(let i=0; i<nums.length;i++){
        let key = target - nums[i]
        if(newMap.has(key)){
            return [newMap.get(key), i]
        }
        newMap.set(nums[i], i)
    }
};
```

2020-07-23 07:17 UTC, littlepurple commented
```
function target(arr, nums) {
  for (let i = 0; i < arr.length; i++) {
    if (nums > arr[i]) {
      const diff = nums - arr[i]
      const index = arr.indexOf(diff)
      if (index !== -1 && index !== i) return [i, index]
    }
  }
  return '404 没有找到啦'
}
```

2020-07-28 10:21 UTC, jackchang2015 commented
```javascript
const twoSum = (nums, target) =>{
    const map = {};
    for(let i = 0, ln = nums.length; i < ln; i++){
        let p = target - nums[i];
        if(map[p] !== undefined){
            return [map[p], i];
        }
        map[nums[i]] = i;
    }
    return false;
};

twoSum([4, 4, 11, 15], 8); // [0, 1]
```

2020-08-07 01:10 UTC, haoguofen commented
```javascript
        const arr = [1, 9, 3, 5, 5, 5, 2, 99, 4, 24, 0, 10, 8, 2, 8]
        const target = 10

        function lime([...arr], target) {
            const result = []
            for (let i = 0; i < arr.length; i++) {
                for (let j = 0; j < arr.length; j++) {
                    if (i === j) continue
                    if (arr[i] + arr[j] === target) {
                        result.push(arr[i], arr[j])
                        arr[i] = arr[j] = undefined
                    }
                }
            }
            return result
        }

        console.log(lime(arr, target))  //(10) [1, 9, 5, 5, 2, 8, 0, 10, 2, 8]
```

2020-08-24 03:40 UTC, jackchang2015 commented
> ```
> 
> function convert(arr, target) {
>       for(let i in arr) {
>           const test = target - arr[i];
>           if(arr.includes(test, i)) {
>               return [arr.indexOf(arr[i]), arr.indexOf(test)];
>           }
>      }
>      return '未找到';
> }
> ```

convert([4, 3, 4, 15], 8);这个就有问题咯

2020-10-11 12:28 UTC, wangdong2333 commented
const twoSum = function (arr, target) {
      let len = srr.length;
      let obj = {};
      for (let i = 0; i < len; i++) {
        if (obj[target - arr[i]] !== undefined) {
          return [obj[target - arr[i]], i];
        }
        obj[arr[i]] = i;
      }
    }
    console.log(twoSum([3, 2, 4], 6));//[1,2]

2020-10-11 12:28 UTC, wangdong2333 commented
`const twoSum = function (arr, target) {
      let len = srr.length;
      let obj = {};
      for (let i = 0; i < len; i++) {
        if (obj[target - arr[i]] !== undefined) {
          return [obj[target - arr[i]], i];
        }
        obj[arr[i]] = i;
      }
    }
    console.log(twoSum([3, 2, 4], 6));`

2020-12-16 13:49 UTC, tangli06 commented
let nums = [0, 2, 7, 12, 11, 3, 14];
const sums = (nums, val) => {
  let tempArr = [];
  let numsLen = nums.length;
  for(let i = 0; i < numsLen; i++) {
    let tempVal = nums[i];
    for (let j = i + 1; j < numsLen; j++) {
      if (tempVal + nums[j] == val) {
        tempArr.push([i, j]);
      }
    }
  }
  console.log(tempArr);
}
sums(nums, 14);

2021-01-11 08:57 UTC, qinlixun commented
```
function findMatch(nums, target) {
    let obj = {}, res = [];
    for (let num of nums) {
        obj[num] = target - num
    }
    for (let i in obj) {
        if (obj[obj[i]] + obj[i] == target)
        res.push([parseInt(i),obj[i]]);
    }
    return res.filter(arr => arr[0] <= arr[1]);
}
```
我输出的是一个二维数组，每个子数组是一组加数的组合
两个不嵌套的循环，复杂度应该是O(n)吧？

2021-02-21 14:53 UTC, huxiaocheng commented
如果数组是无序的：o(n)的空间+o(n)的时间
function find(arr, target) {
  const map = new Map();
  for (let i = 0; i < arr.length; i++) {
    const diff = target - arr[i];
    if (!map.has(diff)) {
      map.set(arr[i], i);
    } else {
      return [map.get(diff), i];
    }
  }
}

如果数组是有序的：o(1)的空间 + o(n)的时间
function find(arr, target) {
  let l = 0;
  let r = arr.length - 1;
  while (r > l) {
    if (arr[l] + arr[r] > target) {
      r--;
    } else if (arr[l] + arr[r] < target) {
      l++;
    } else {
      return [l, r];
    }
  }
}

2021-02-24 00:46 UTC, Ori253 commented
用API的话还是容易的，这题在LeetCode上也是简单难度
```
function find(arr, target) {
            let res = [], // 存放已经测试过的元素
                index = null;
            for (let i = 0; i < arr.length; i++) {
                if (res.includes(target - arr[i])) {
                    continue;
                }
                else {
                    index = arr.indexOf(target - arr[i], i + 1);
                    if (index === -1) {
                        res.push(target - arr[i]);
                    }
                    else {
                        return [i, index];
                    }
                }
            }
        }
```

2021-03-01 07:12 UTC, Orime112 commented
```javascript
const findSum = (nums, target) => {
  const obj = {}
  for(let i = 0; i < nums.length; i++){
    const val = nums[i]
    if(typeof obj[val] !== 'undefined'){
      return [obj[val], i]
    } else {
      obj[target - val] = i
    }
  }
}
const nums = [2, 7, 11, 15], target = 9
console.log(findSum(nums, target))
```

2021-03-15 08:45 UTC, ZhengXiaowei commented
```
function twoSum(nums, target) {
   for(let i = 0; i < nums.length; i++) {
     let nums_slice = nums.slice(0);
     let result = target - nums[i];
     nums_slice.splice(i, 1);
     if (!!~nums_slice.indexOf(result)) {
        let result_key = nums_slice.indexOf(result) + 1;
        return [i, result_key];
     }
     continue;
   }
}
```

2021-03-24 17:15 UTC, hstair commented
双指针，两个额外的变量，时间复杂度O（n）
```javascript
function findSumIndex (nums, target) {
  let left = 0
  let right = nums.length - 1
  while (left < right) {
    const sum = nums[left] + nums[right]
    if (sum > target) {
      right--
    } else if (sum < target) {
      left++
    } else {
    	return [left, right]
    }
  }
}
```

2021-03-24 17:16 UTC, vdorchan commented
双指针，两个额外的变量，时间复杂度O（n）
```javascript
function findSumIndex (nums, target) {
  let left = 0
  let right = nums.length - 1
  while (left < right) {
    const sum = nums[left] + nums[right]
    if (sum > target) {
      right--
    } else if (sum < target) {
      left++
    } else {
    	return [left, right]
    }
  }
}
```

2021-05-06 11:25 UTC, xiangergou commented
```js
nums = [2, 11, 7, 15], target = 9
try {
	nums.forEach((k, v) => {
    nums.splice(v, 1, undefined)
    nums.forEach((kk, vv) => {
      if (k + kk === target) {
				throw Error([v ,vv])
      }
    })
  })
} catch(data){
	console.log(data)
}
```

2021-05-10 10:15 UTC, zhelingwang commented
用差值和`lastIndexOf`比较简单
```js
function fn(arr, target) {
  for (let i = 0; i < arr.length; i++) {
    const find = target - arr[i];
    const idx = arr.lastIndexOf(find);
    if (idx !== -1 && idx !== i) {
      return [i, idx];
    }
  }
  return [];
}

console.log(fn([2, 7, 11, 15], 9));  // [0,1]
console.log(fn([2, 4, 15], 8));  // []
console.log(fn([2, 4, 4, 15], 8)); // [1,2]
console.log(fn([2, 4, 8, 0, 3, 4, 15], 7)); //[1,4]
```

2021-06-23 16:02 UTC, NikaSSL commented
```js
function searchTargetIndex(arr, target) {
  const map = new Map()
  for (let index = 0; index < arr.length; index++) {
    const curVal = arr[index]
    const restval = target - curVal
    if (map.has(restval)) {
      return [map.get(restval), index]
    } else {
      map.set(curVal, index)
    }
  }
  return []
}

console.assert(JSON.stringify(searchTargetIndex([2, 7, 11, 15], 9)) === JSON.stringify([0, 1]))
console.assert(JSON.stringify(searchTargetIndex([4, 7, 11, 15], 8)) === JSON.stringify([]))
```

2021-07-05 04:55 UTC, pch1024 commented
`
var arr = [4, 7, 11, 15, 4, 3, 15];

function find(arr, sum) {
    var map = {};
    var result = [];
    for (let i = 0; i < arr.length; i++) {
        var n = arr[i];
        if (map[sum - n] === undefined) {
            map[arr[i]] = i;
        } else {
            result.push([map[sum - n], i]);
        }
    }
    return result;
}

console.log(find(arr, 8)); // [ [ 0, 4 ] ]
console.log(find(arr, 26)); // [ [ 2, 3 ], [ 2, 6 ] ]
console.log(find(arr, 11)); // [ [ 0, 1 ] ]
`

2021-07-05 05:17 UTC, pch1024 commented
```js
var arr = [4, 7, 11, 15, 4, 3, 15];
function find(arr, sum) {
    var map = {};
    var result = [];
    for (let i = 0; i < arr.length; i++) {
        var n = arr[i];
        if (map[sum - n] !== undefined) {
            map[sum - n].forEach((index) => {
                result.push(index + "-" + i);
            });
        }
        if (map[n]) {
            map[n].push(i);
        } else {
            map[n] = [i];
        }
    }
    return result;
}

console.log(find(arr, 8));
console.log(find(arr, 26));
console.log(find(arr, 11));
// [ '0-4' ]
// [ '2-3', '2-6' ]
// [ '0-1', '1-4' ]

```

2021-07-08 01:40 UTC, wangShengCool commented
function match(arr, target) {
        let index = 0;
        let res = [];
        for (let i = 0; i <= arr.length; ++i) {
          if (index >= arr.length) {
            return;
          }
          if (index !== i) {
            if (arr[index] + arr[i] === target) {
              res.push(arr[index], arr[i]);
              return res;
            } else {
              index++;
            }
          }
        }
        return res;
      }
      这是我的答案，如有欠缺，欢迎各位大佬指正~

2021-08-16 09:10 UTC, gzsendiEhc commented
function numSum (nums, target) {
    let maps = {}
    nums.forEach((item,i) => {
        nums.forEach((item2,j) => {
            if (i !== j) {
                let count = item + item2
                
                if (count === target) {
                    maps[i] = i
                    maps[j] = j
                }
            }
        })
    })
    console.log(maps)
    return Object.keys(maps).map(item => maps[item])
}
var nums = [2, 7, 11, 15, 8 ,1, 4, 5], target = 9
console.log(numSum(nums, target))

2021-08-16 09:10 UTC, gzsendiEhc commented
`function sum (nums, target) {
    let maps = {}
    nums.forEach((item,i) => {
        nums.forEach((item2,j) => {
            if (i !== j) {
                let count = item + item2
                
                if (count === target) {
                    maps[i] = i
                    maps[j] = j
                }
            }
        })
    })
    console.log(maps)
    return Object.keys(maps).map(item => maps[item])
}
var nums = [2, 7, 11, 15, 8 ,1, 4, 5], target = 9
console.log(sum(nums, target))`

2021-08-30 10:31 UTC, gogopaner commented
`let nums = [1, 2, 3, 4, 5, 6, 7, 11, 15];
        let target = 9;
        let c = 0;
        let list = [];

        function search(one, two = null) {
            for (let i = c; i < nums.length; i++) {
                if (i < nums.length - 1) {
                    two = nums[(i + 1)];
                    if (one + two === target) {
                        list = [c, i + 1]
                        break;
                    } else {
                        if (i === nums.length - 2) {
                            c += 1;
                            search(nums[c]);
                        }
                    }
                }
            }
            return list

        }

        console.log(search(nums[c]), 'search()search()');`

2021-09-15 09:57 UTC, 523451928 commented
```
var twoSum = function(nums, target) {
  const obj = {}
  for (let i = 0; i < nums.length; i++) {
    const num = nums[i];
    if (num in obj) {
      return [obj[num], i]
    } else {
      obj[target - num] = i
    }
  }
};

2021-10-21 06:42 UTC, xiangfei1 commented
```js
function sumofTwo(arr,target){
  let res = [];
  for(let i=0;i<arr.length;i++){
     let flag = arr.indexOf(target -arr[i]);   //目标值减去数组中某一个元素，并判断 差 是否在数组中存在
     if(flag !== -1 && flag !== i) {   //不为-1，并且索引不等于当前元素（排除如2+2 = 4等），不过这里如果是相同的元素，获取的索引会看上去有点别扭
          res.push(i,flag);
          break;   //如题，结果唯一
     }
    }
  return res;
}
console.log(sumofTwo([5,5,10,15],10);  //[1,0]，这里根据循环判断，i=0时，因为indexOf找到的索引也是0，所以跳过了，i=1时，满足if条件，即结果为[1,0]
console.log(sumofTwo([5,0,10,15],10);  //[1,2]
```

2021-10-28 03:06 UTC, mygod48 commented
使用Map，记录目前已经遍历过的数字中，达到target所需要的“另一半”数字的值，以及对应的“原配”索引。
Map结构：{key: “另一半”数字的值, value: “原配”索引}
遍历时，首先检测是否已经存在“另一半”，如果存在就直接返回记录的“原配”索引，以及当前迭代的数组下标。
如果没有，则计算当前数字所需要的“另一半”，与当前数组下标一同记录在Map中。

由于是先检测是否匹配再添加新键值对，所以不会出现indexOf检测中 arr = [4] 可以达成 target = 8的情况，也不需要额外进行检测。

```
function sumofTwo(arr, target) {
    const needMap = new Map();

    for (let i = 0; i < arr.length; i++) {
        const num = arr[i];

        if(needMap.has(num)) {
            return [needMap.get(num), i];
        }

        const needNum = target - num;
        needMap.set(needNum, i);
    }

    return [];
}

sumofTwo([2, 7, 11, 15], 9);
```

2021-11-13 09:08 UTC, yaochengGit commented
```
let arr = [1, 2, 3, 4, 7],
            num = 7;

function findNum(arr, num) {
    let res = [];
    for (let i = 0; i < arr.length; i++) {
        for (let j = 0; j < arr.length; j++) {
            if (num - arr[i] == arr[j]) {
                res.push(i, j);
                return res
            }
        }
    };
}
findNum(arr, num)
```

2021-11-13 09:17 UTC, yaochengGit commented
```

        function findNum(arr, num) {
            let res = [];
            for (let i = 0; i < arr.length; i++) {
                for (let j = 0; j < arr.length; j++) {
                    if(arr[i] == arr[j] && i == j) {
                        continue
                    }
                    if (num - arr[i] == arr[j]) {
                        res.push(i, j);
                        console.log(res)
                        return res
                    }
                }
            };
        }
        findNum(arr, num)
```

2021-11-18 14:26 UTC, hdsuperman commented
```js
const nums = [2,7,11,15, 3, 4, 6, 4, 5];
const target = 9;
const result = [];

for(let i = 0, len = nums.length; i < len; i++) {
  // if(nums[i] > target) continue;
  const idx = nums.findIndex(e => e === target - nums[i]);
  if(idx > i) result.push([i,idx]);
}

console.log('result', result);
```

2021-11-18 14:29 UTC, hdsuperman commented
```js
const nums = [2,7,11,15, 3, 4, 6, 4, 5];
const target = 9;
const result = [];
const used = [];

for(let i = 0, len = nums.length; i < len; i++) {
  if(used.includes(i)) continue;
  const idx = nums.findIndex(e => e === target - nums[i]);
  if(idx > i && !used.includes(idx)) {
    result.push([i,idx]);
    used.push(i, idx);
  }
}

console.log('result', result);
```

2021-11-26 07:24 UTC, Dreams-set-sail commented
function fn1(nums, target) {
      let map = Object.create(null)
      for (let i = 0; i < nums.length; i++) {
        let val = nums[i]
        if (map[val] !== undefined) {
          return [map[val], i]
        } else {
          map[target - val] = i
        }
      }
    }

2021-12-23 08:23 UTC, SnailOwO commented
```js
 let target = 9
    let nums = [2, 3, 1, 2, 1, 9, 7, 12, 8, 11, 15, ]

    function check(numAry = nums, tag = target) {
        const res = []

        for (let i = 0; i < numAry.length - 1; i++) {
            for (let j = i + 1; j < numAry.length; j++) {
                if (numAry[i] !== numAry[j] &&
                    (numAry[i] + numAry[j]) === tag
                ) {
                    res.push(i, j)
                    return res
                }
            }
        }
        return res
    }

    console.log(check());

2021-12-26 04:31 UTC, fenglizhu commented
```
function result(list, target) {
    let map = {};
    let result = []
    for (let i = 0; i < list.length; i++) {
        let reduce = target - list[i];
        if(reduce > 0) map[list[i]] = i;
        if(map.hasOwnProperty(reduce)){
            result.push(map[reduce], i)
            break
            // 如果想要查找所有的,去掉break,执行下面的
            result.push([map[reduce], i])
        }
    }
    return result
}
```

2022-02-25 08:26 UTC, Four-Names commented
```js
let towNumSum = function (arr, num) {
  for (let i = 0; i < arr.length; i++) {
    let j = arr.indexOf(num - i, i);
    if (j != -1) return [i, j];
  }
};
```

2022-03-21 03:32 UTC, sexnmaa commented
Map， 空间换时间
```
var twoSum = function(nums, target) {
    let map = new Map()
  for (let i = 0; i < nums.length; i++) {
    if (map.has(target - nums[i])) {
      return [i, map.get(target - nums[i])]
    }
    map.set(nums[i], i)
  }
};
```

2022-04-12 13:19 UTC, jok-ashun commented
```js
var sumOfTwoNumber = function (array, target) {
    let map = {};
    for (let i = 0; i < nums.length; i++) {
        let d = target - nums[i];
        if (map[d] !== undefined) {
            return [map[d], i];
        }
        map[nums[i]] = i;
    }
    return [];
}
var nums = [2, 7, 11, 15];
var target = 9
console.log(sumOfTwoNumber(nums, target));
```

2022-04-12 13:20 UTC, Vera1128 commented
这是一封自动回复邮件。您好，你的邮件我已收到，会尽快给您回复，祝您生活愉快！

2022-04-20 01:17 UTC, liushan-github commented
function getTwo(target,arr){
  for(let i=0;i<arr.length;i++){
    let first=arr[i];
    let second=arr[i+1];
    if(first+second==target){
      return [first,second]
    }
    if(i==arr.length-1){
      return '没有找到'
    }
  }
}

console.log(getTwo(10,[4,2,5,6,8,20]))

2022-04-20 01:21 UTC, liushan-github commented
function getTwo(target,arr){
  for(let i=0;i<arr.length;i++){
    let first=arr[i];
    let second=arr[i+1];
    if(first+second==target){
      return [first,second]
    }
    if(i==arr.length-1){
      return '没有找到'
    }
  }
}

console.log(getTwo(10,[4,2,5,6,8,20]))

2022-04-20 01:30 UTC, liushan-github commented
```
function getTwo(target, arr) {
  for (let i = 0; i < arr.length; i++) {
    const first = arr[i];
    const second = arr[i + 1];
    if (first + second === target) {
      return [i, i + 1]
    }
    if (i === arr.length - 1) {
      return '没有找到'
    }
  }
}

console.log(getTwo(10, [4, 2, 4, 6, 8, 20]))
```

2022-06-08 09:14 UTC, 523451928 commented
`
function twoSum(nums, target) {
  const obj = {}
  for (let i = 0; i < nums.length; i++) {
    if (nums[i] in obj) {
      return [obj[nums[i]], i];
    } else {
      obj[target - nums[i]] = i;
    }
  }
}
`

2022-06-08 09:15 UTC, 523451928 commented
```
function twoSum(nums, target) {
  const obj = {}
  for (let i = 0; i < nums.length; i++) {
    if (nums[i] in obj) {
      return [obj[nums[i]], i];
    } else {
      obj[target - nums[i]] = i;
    }
  }
}
```

2022-06-08 09:15 UTC, Vera1128 commented
这是一封自动回复邮件。您好，你的邮件我已收到，会尽快给您回复，祝您生活愉快！

2022-07-06 10:54 UTC, hzfvictory commented
> 利用空间换时间：
> 
> ```js
> const twoNum = (nums, target) => {
>     const maps = {};
>     for(let i = 0, len = nums.length; i < len; i++) {
>         let diff = target - nums[i];
>         if (maps[diff] > -1) {
>             return [maps[diff], i];
>         }
>         maps[nums[i]] = i;
>     }
>     return [];
> }
> ```

twoNum([1,2,3,4,5,6],7)   输出 【2,3】

2022-07-06 10:55 UTC, Vera1128 commented
这是一封自动回复邮件。您好，你的邮件我已收到，会尽快给您回复，祝您生活愉快！

2023-01-06 09:17 UTC, tanjunfeng commented
let nums = [2, 7, 11, 15, 17, 25]
let target = 36
let list = []
nums.forEach((v, index) => {
    if (nums.includes(target - v)) {
      list.push(index, nums.findIndex(j => j === target - v))
    }
})
console.log([...new Set(list)])

2023-01-09 02:18 UTC, tanjunfeng commented
let nums = [2, 7, 11, 15]
let target = 9
let list = []
nums.forEach((v, index) => {
    if (nums.includes(target - v)) {
      list.push(index, nums.findIndex(j => j === target - v))
    }
})
console.log([...new Set(list)])

2023-02-25 02:30 UTC, benzhemin commented
```javascript
const findSumTarget = (numList, target) => {
    const end = numList.length;
    const pairList = [];
    for (let i=0; i<end; i++) {
        for (let cursor = i+1; cursor < end; cursor++) {
            if (numList[i] + numList[cursor] === target) {
                pairList.push([numList[i], numList[cursor]]);
                break;
            }
        }
    }

    return pairList;
}

const findSumTargetSimple = (numList, target) => {
    const pairList = [];

    numList.forEach((v, i) => {
        numList.slice(i+1).forEach(item =>
            v + item === target && pairList.push([v, item])
        )
    });

    return pairList;
}

const input = [2, 7, 11, 15, 1, 3, 6, 1, 9, 8];

const pairList = findSumTarget(input, 9);
console.log(pairList);

const pairListSimple = findSumTargetSimple(input, 9);
console.log(pairListSimple);
```

2023-04-19 07:45 UTC, gz281620758 commented
function sumInArr(arr, target) {
    let res = []
    for (let i = 0; i < arr.length; i++) {
        for (let j = arr.length - 1; j > 0; j--) {
            if (arr[i] + arr[j] == target&&i<j) {
                res.push(i, j)
                break
            }
        }
    }
    return res
}
sumInArr([2, 7, 11, 15], 9)

2023-05-31 22:37 UTC, qifengla commented
```
function twoSum(nums, target) {
  const hashMap = new Map();

  for (let i = 0; i < nums.length; i++) {
    const complement = target - nums[i];
    if (hashMap.has(complement)) {
      return [hashMap.get(complement), i];
    }
    hashMap.set(nums[i], i);
  }

  return []; // 如果不存在符合条件的两个数，则返回空数组
}
```